
detectors:
  Attribute:
    enabled: false
  TooManyInstanceVariables:
    enabled: false
  TooManyStatements:
    enabled: false
  NilCheck:
    enabled: false
  RepeatedConditional:
    enabled: false
  FeatureEnvy:
    exclude:
      - "RobotField#simulate"

exclude_paths:
  - tests/
