
detectors:
  Attribute:
    enabled: false
  TooManyInstanceVariables:
    enabled: false
  TooManyStatements:
    enabled: false
  NilCheck:
    exclude:
      - "StringProcessor#self.parse"
  FeatureEnvy:
    exclude:
      - "RobotField#simulate"


exclude_paths:
  - tests/