
AllCops:
  NewCops: enable
  Exclude:
    - 'tests/**/*'

RSpec:
  Enabled: false

Layout/LineLength:
  Max: 99

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15

plugins:
  - rubocop-minitest

