name: Test and Package Robot
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.4', '4.0']
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Tests
      run: bundle exec minitest tests
    # - name: Rubocop
    #   run: bundle exec rubocop
    - name: Bundler Audit
      run: bundle exec bundler-audit
    - name: Brakeman
      run: bundle exec brakeman . -A --no-pager --force
    - name: Reek
      run: bundle exec reek
    - name: Flog
      run: bundle exec flog --score
    - name: Flay
      run: bundle exec flay --summary
    - name: Run Minimum Stress Checks
      run: ruby -e 'puts "hi, one day im going to grow up into a real tiny stress test"'

  release:
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
    - name: Zip Release
      run: zip --recurse-paths release.zip . --exclude ".git/*"
    - name: Create and Upload latest release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          release.zip
